package entity

data class InfoResult(
    var dataItems: List<DataItem>? = null,
    var message: String = "",
    var resultCode: Int = -1,
    var seqId: String = "",
    var serviceId: String = "",
    var constCarNo :String = ""
)


data class DataItem(
    val attributes: AttributesItem,
    val objectId: String,
    val operateType: String
)

data class AttributesItem(
    val KDAttachCoupons: Any,
    val accessSource: Any,
    val attach: String,
    val attentionPhoto: String,
    val attentionRemark: String,
    val attentionUrl: String,
    val businesserCode: String,
    val businesserId: String,
    val carNo: String,
    val car_id: Any,
    val cardNo: String,
    val copycarno: String,
    val couponNo: String,
    val couponType: Any,
    val couponValue: Any,
    val couponYhType: Any,
    val coupon_num: String,
    val coupon_use_mode: String,
    val createTime: String,
    val curType: String,
    val deductFee: Double,
    val discountFee: Double,
    val discountId: String,
    val endTime: String,
    val freeMinute: String,
    val free_minute: String,
    val from: Any,
    val goodName: String,
    val goodTitle: String,
    val id: String,
    val isShow: String,
    val isStat: Int,
    val is_integral: String,
    val is_lock: Int,
    val is_map: Int,
    val isvId: String,
    val joinType: Int,
    val joint_mode: String,
    val joint_type: String,
    val memberMode: String,
    val member_mode: String,
    val merGID: String,
    val orderNo: String,
    val orderStatus: Int,
    val orderType: String,
    val otherFee: Double,
    val parkCode: String,
    val parkId: String,
    val parkInId: String,
    val parkName: String,
    val plateColor: String,
    val policyMinute: String,
    val policy_minute: String,
    val quickExit: String,
    val receiptOperator: Any,
    val retcode: String,
    val retmsg: String,
    val rule_remark: String,
    val rule_source: String,
    val send_code_direction: String,
    val seqId: String,
    val serviceFee: Double,
    val serviceId: String,
    val serviceTime: Int,
    val startTime: String,
    val subsystemUrl: String,
    val surplusMinute: String,
    val surplus_minute: String,
    val totalFee: Double,
    val transportFee: Double,
    val url: String,
    val url1631: String,
    val userId: String,
    val validTimeLen: Int
)
